export const ACTION_TYPES = {
    TASK_LIST_REQUEST: 'TASK_LIST_REQUEST',
    TASK_LIST_SUCCESS: 'TASK_LIST_SUCCESS',
    TASK_LIST_FAIL: 'TASK_LIST_FAIL',

    TASK_DETAIL_REQUEST: 'TASK_DETAIL_REQUEST',
    TASK_DETAIL_SUCCESS: 'TASK_DETAIL_SUCCESS',
    TASK_DETAIL_FAIL: 'TASK_DETAIL_FAIL',
}